### ISSUE TITLE
Google Maps included in index.html

### ISSUE THREAD

**Issue by ncardeli** [sinergise/SentinelPlayground#3]
Hi! I noticed that Google Maps API is being included in [index.html](../blob/master/public/index.html). The thing is I think it isn't being used anywhere.
I removed it and everything seems to work just fine. 

Thanks

**Comment by themre** [comment]
No, you need this API lib for the search box to work. It uses their Geocoding API. If you don't specify any API key, you can only make 2k requests/day. If you provide some, you have up to 25k requests/day.
